import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"

export default function PrivacyPage() {
  return (
    <div className="container py-16 space-y-16">
      {/* Hero Section */}
      <div className="max-w-4xl mx-auto space-y-4">
        <h1 className="text-4xl font-bold tracking-tighter text-center sm:text-5xl">
          Privacy{" "}
          <span className="bg-gradient-to-r from-blue-600 to-violet-600 bg-clip-text text-transparent">
            Policy
          </span>
        </h1>
        <p className="text-sm text-muted-foreground text-center">Updated at January 3rd, 2025</p>
      </div>

      {/* Introduction */}
      <Card className="border-2">
        <CardContent className="pt-6 space-y-4">
          <p>
            Botintelli ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how your
            personal information is collected, used, and disclosed by Botintelli.
          </p>
          <p>
            This Privacy Policy applies to our website, and its associated subdomains (collectively, our "Service")
            alongside our application, Botintelli. By accessing or using our Service, you signify that you have read,
            understood, and agree to our collection, storage, use, and disclosure of your personal information as described
            in this Privacy Policy and our Terms of Service.
          </p>
        </CardContent>
      </Card>

      {/* Definitions */}
      <Card className="border-2">
        <CardHeader>
          <CardTitle>Definitions and Key Terms</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <p>To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are
            referenced, are strictly defined as:</p>
          <ul className="space-y-4 list-disc list-inside">
            <li><strong>Cookie:</strong> small amount of data generated by a website and saved by your web browser. It is used to
              identify your browser, provide analytics, remember information about you such as your language
              preference or login information.</li>
            <li><strong>Company:</strong> when this policy mentions "Company," "we," "us," or "our," it refers to Literatitech Solutions
              Pvt. Ltd., (2064, Felicita Tower, Mahagun Moderne, Sector 78, Noida, U.P, PIN 201301), that is
              responsible for your information under this Privacy Policy.</li>
            <li><strong>Country:</strong> where Botintelli or the owners/founders of Botintelli are based, in this case is India</li>
            <li><strong>Customer:</strong> refers to the company, organization or person that signs up to use the Botintelli Service to
              manage the relationships with your consumers or service users.</li>
            <li><strong>Device:</strong> any internet connected device such as a phone, tablet, computer or any other device that can be
              used to visit Botintelli and use the services.</li>
            <li><strong>IP address:</strong> Every device connected to the Internet is assigned a number known as an Internet protocol
              (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to
              identify the location from which a device is connecting to the Internet.</li>
            <li><strong>Personnel:</strong> refers to those individuals who are employed by Botintelli or are under contract to perform a
              service on behalf of one of the parties.</li>
            <li><strong>Personal Data:</strong> any information that directly, indirectly, or in connection with other information —
              including a personal identification number — allows for the identification or identifiability of a natural
              person.</li>
            <li><strong>Service:</strong> refers to the service provided by Botintelli as described in the relative terms (if available)
              and on this platform.</li>
            <li><strong>Third-party service:</strong> refers to advertisers, contest sponsors, promotional and marketing partners, and
              others who provide our content or whose products or services we think may interest you.</li>
            <li><strong>Website:</strong> Botintelli's site, which can be accessed via this URL: www.botintelli.com</li>
            <li><strong>You:</strong> a person or entity that is registered with Botintelli to use the Services.</li>
          </ul>
        </CardContent>
      </Card>

      {/* Information Collection */}
      <Card className="border-2">
        <CardHeader>
          <CardTitle>Information Automatically Collected</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <p>
            There is some information like your Internet Protocol (IP) address and/or browser and device characteristics
            — is collected automatically when you visit our platform. This information may be used to connect your
            computer to the Internet.
          </p>
          <p>
            We automatically collect certain information when you visit, use or navigate the platform. This information
            does not reveal your specific identity (like your name or contact information) but may include device and
            usage information, such as:
          </p>
          <ul className="list-disc list-inside space-y-2">
            <li>IP address</li>
            <li>Browser and device characteristics</li>
            <li>Operating system</li>
            <li>Language preferences</li>
            <li>Referring URLs</li>
            <li>Device name</li>
            <li>Country and location</li>
            <li>Usage information</li>
          </ul>
        </CardContent>
      </Card>

      {/* GDPR Information */}
      <Card className="border-2">
        <CardHeader>
          <CardTitle>Information about General Data Protection Regulation (GDPR)</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <p>
            We may be collecting and using information from you if you are from the European Economic Area (EEA), and in
            this section of our Privacy Policy we are going to explain exactly how and why is this data collected, and
            how we maintain this data under protection from being replicated or used in the wrong way.
          </p>
          <h3 className="text-xl font-semibold mt-6">What is GDPR?</h3>
          <p>
            GDPR is an EU-wide privacy and data protection law that regulates how EU residents' data is protected by
            companies and enhances the control the EU residents have, over their personal data.
          </p>
          <h3 className="text-xl font-semibold mt-6">Data Protection Principles</h3>
          <ul className="list-disc list-inside space-y-2">
            <li>Personal data collected must be processed in a fair, legal, and transparent way</li>
            <li>Personal data should only be collected to fulfil a specific purpose</li>
            <li>Personal data should be held no longer than necessary to fulfil its purpose</li>
            <li>People have the right to access their own personal data</li>
          </ul>
        </CardContent>
      </Card>

      {/* Contact Information */}
      <Card className="border-2">
        <CardHeader>
          <CardTitle>Contact Us</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <p>Don't hesitate to contact us if you have any questions.</p>
          <p>Via this Link: <a href="https://www.botintelli.com/contact" className="text-blue-600 hover:underline">https://www.botintelli.com/contact</a></p>
        </CardContent>
      </Card>

      {/* Footer Note */}
      <div className="text-center text-sm text-muted-foreground">
        <p>This Privacy Policy was last updated on January 3rd, 2025</p>
      </div>
    </div>
  )
}

